.TH GMTKBABEL 1
.SH NAME
gmtkbabel - Zenity GUI to mtkbabel
.SH SYNOPSIS
.PP
.B gmtkbabel
.SH DESCRIPTION
This manual page documents briefly the \fBgmtkbabel\fR command.
.PP
\fBgmtkbabel\fR consists of a set of shell scripts that, using
\fBzenity\fR, provide a graphical interface to the command-line
program \fBmtkbabel\fR.
.SH SEE ALSO
.BR mtkbabel (1)
.SH AUTHOR
\fBgmtkbabel\fR was written by David Paleino <d.paleino@gmail.com>
and Elena Grandi.
.SH HOMEPAGE
The project homepage is located at:
.br
http://dpaleino.github.com/gmtkbabel/
